### ISSUE TITLE
to_dictionary() to_lookup() default for Grouping

### ISSUE THREAD

**Issue by Sovetnikov** [sixty-north/asq#13]
Just a suggestion, that Grouping.to_dictionary() without key and value selectors must behave as to_dictionary(key_selector=lambda x: x.key, value_selector=lambda x: x.to_list())
Just make dict with key->list_of_values structure.

Same for to_lookup()

**Comment by rob-smallshire** [comment]
Good idea!

**Comment by rob-smallshire** [comment]
Closing this issue now that documentation is in place.  This change will be included in the next release of asq.
